[package]
name = "llmbundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
arboard = "3.4.1"
clap = { version = "4.5.28", features = ["derive"] }
globset = "0.4.15"
ignore = "0.4.23"
shellexpand = "3.1.0"
rayon = "1.10.0"
colored = "3.0.0"
